app = "football-scraper"  # your chosen Fly app name
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  PA_TOKEN = "ignore"  # we'll set the real one on Fly.io

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80
