name: Scrape upcoming Matches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run scraper script
      run: python upcoming_scraper.py

    - name: Upload to PythonAnywhere
      run: |
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/Michael1/files/path/home/Michael1/predictsite/upcoming_matches.json" \
          --header "Authorization: Token ${{ secrets.PYTHONANYWHERE_TOKEN }}" \
          --data-binary "@upcoming_matches.json"
